name: Generate Release
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sitemaps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Fetch Sitemaps
    steps:
      - name: Fetch Sitemap Index
        run: |
          wget \
            --no-verbose \
            --tries 3 \
            --waitretry 10 \
            --retry-on-http-error 500,503 \
            --user-agent "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --output-document sitemapindex.xml \
            'https://chromewebstore.google.com/sitemap'
      - name: Extract Sitemap URLs
        run: |
          grep -F '<loc>' ./sitemapindex.xml | 
            awk -F '[<>]' '{ gsub(/&amp;/, "\\&", $3); print $3 }' > sitemapindex.txt
      - name: Fetch Sitemap Shards
        run: |
          sort --random-sort ./sitemapindex.txt |
          grep -v "&hl=" |
          parallel \
            --max-procs 10 \
            --max-replace-args 100 \
            --pipe \
            "wget \
              --no-verbose \
              --tries 3 \
              --waitretry 10 \
              --retry-on-http-error 500,503 \
              --user-agent '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}' \
              --directory-prefix . \
              --input-file -"
      - name: Extract URLs
        run: |
          grep -F '<loc>' "sitemap?"* | 
            awk -F '[<>]' '{ gsub(/&amp;/, "\\&", $3); print $3 }' > ./urls.txt
      - name: Extract Extensions
        run: |
          awk -F/ '{ print substr($6, 0, 32) }' ./urls.txt | sort -u > ./extensions.txt
      - name: Compress Sitemaps
        run: |
          tar -cvjSf sitemaps.tar.bz2 *.txt
      - name: Generate Tag
        id: tag
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --repo "$GITHUB_REPOSITORY" \
            --title "${{ steps.tag.outputs.date }}" \
            --notes "Action URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            "${{ steps.tag.outputs.date }}"
      - name: Upload Artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload \
            --repo "$GITHUB_REPOSITORY" \
            "${{ steps.tag.outputs.date }}" \
            "sitemaps.tar.bz2"
