name: Generate Release
on:
  workflow_dispatch:
jobs:
  sitemaps:
    runs-on: ubuntu-20.04
    name: Fetch Sitemaps
    steps:
      - name: Fetch Sitemap Index
        run: |
          wget \
            --no-verbose \
            --tries 3 \
            --waitretry 10 \
            --retry-on-http-error 500,503 \
            --user-agent "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --output-document sitemapindex.xml \
            'https://chrome.google.com/webstore/sitemap'
      - name: Extract Sitemap URLs
        run: |
          grep -F '<loc>' ./sitemapindex.xml | 
            awk -F '[<>]' '{ gsub(/&amp;/, "\\&", $3); print $3 }' > sitemapindex.txt
      - name: Upload Sitemap Index
        uses: actions/upload-artifact@v2
        with:
          name: sitemaps
          path: sitemapindex.txt
      - name: Fetch Sitemap Shards
        run: |
          head -n 10 sitemapindex.txt |
          sort --random-sort |
          parallel \
            --max-procs 10 \
            --max-replace-args 100 \
            --pipe \
            "wget \
              --no-verbose \
              --tries 3 \
              --waitretry 10 \
              --retry-on-http-error 500,503 \
              --user-agent '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}' \
              --directory-prefix . \
              --input-file -"
      - name: Extract URLs
        run: |
          grep -F '<loc>' "sitemap?"* | 
            awk -F '[<>]' '{ gsub(/&amp;/, "\\&", $3); print $3 }' > ./urls.txt
      - name: Upload URLs
        uses: actions/upload-artifact@v2
        with:
          name: sitemaps
          path: urls.txt
      - name: Extract Extensions
        run: |
          awk -F/ '{ print substr($7, 0, 32) }' ./urls.txt > ./extensions.txt
      - name: Upload Extensions
        uses: actions/upload-artifact@v2
        with:
          name: sitemaps
          path: extensions.txt
  details:
    runs-on: ubuntu-20.04
    needs: sitemaps
    name: Fetch Details (${{matrix.prefix}})
    strategy:
      max-parallel: 16
      matrix:
        prefix: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Download URLs
        uses: actions/download-artifact@v2
        with:
          name: sitemaps
          path: sitemaps
      - name: Fetch Details
        run: |
          awk -F'/' '$0 ~ /^${{matrix.prefix}}/ {
            print "https://chrome.google.com/webstore/ajax/detail?pv=20210820&id=" $0
          }' ./sitemaps/extensions.txt | parallel \
            --max-procs 10 \
            --max-replace-args 10000 \
            --pipe \
            "wget \
              --no-verbose \
              --tries 3 \
              --waitretry 10 \
              --retry-on-http-error 500,503 \
              --user-agent '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}' \
              --output-document details.{#}.json \
              --method POST \
              --input-file -" || true
      - name: Extract Details
        run: |
          python extract.py ${{matrix.prefix}}
      - name: Upload Manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests
          path: "manifests-${{matrix.prefix}}.tgz"
      - name: Upload Details
        uses: actions/upload-artifact@v2
        with:
          name: details
          path: "details-${{matrix.prefix}}.tgz"
