name: Generate Release
on:
  workflow_dispatch:
jobs:
  sitemaps:
    runs-on: ubuntu-20.04
    name: Fetch Sitemaps
    steps:
      - name: Setup Environment
        run: |
          pip install yq
      - name: Fetch Sitemap Index
        run: |
          wget \
            --no-verbose \
            --tries 3 \
            --waitretry 10 \
            --retry-on-http-error 500,503 \
            --user-agent "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            --output-document sitemapindex.xml \
            'https://chrome.google.com/webstore/sitemap'
      - name: Extract Sitemap URLs
        run: |
          xq \
            --raw-output \
            '.sitemapindex.sitemap[]?.loc' \
            ./sitemapindex.xml > sitemapindex.txt
      - name: Fetch Sitemap Shards
        run: |
            sort --random-sort sitemapindex.txt |
            parallel \
              --max-procs 10 \
              --max-replace-args 100 \
              --pipe \
              "wget \
                --no-verbose \
                --tries 3 \
                --waitretry 10 \
                --retry-on-http-error 500,503 \
                --user-agent '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}' \
                --directory-prefix . \
                --input-file -"
      - name: Rename Sitemap Shards
        run: |
          for i in "sitemap?"*; do
            mv "$i" "$(echo "$i.xml" | sed -e 's/[?&]/_/g' -e 's/=/-/g')"
          done
      - name: Archive Sitemaps
        run: |
          zip \
            --junk-paths \
            --recurse-paths "sitemap.zip" \
            sitemap*.xml
      - name: Extract URLs
        run: |
          ls -1 "sitemap_"*".xml" | xargs -n200 -P10 xq --raw-output ".urlset.url[]?.loc" > sitemap.txt
      - name: Upload URLs
        uses: actions/upload-artifact@v2
        with:
          name: sitemaps
          path: |
            sitemap.zip
            sitemapindex.txt
            sitemap.txt
  details:
    runs-on: ubuntu-20.04
    needs: sitemaps
    name: Fetch Details (${{matrix.prefix}})
    strategy:
      max-parallel: 16
      matrix:
        prefix: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p']
    steps:
      - name: Download URLs
        uses: actions/download-artifact@v2
        with:
          name: sitemaps
          path: sitemaps
      - name: Extract URLs
        run: |
          awk -F'/' '$7 ~ /^${{matrix.prefix}}/ {
            print "https://chrome.google.com/webstore/ajax/detail?pv=20210820&id=" substr($7,0,32)
          }' ./sitemaps/sitemap.txt > details.txt
      - name: Fetch Details
        run: |
          cat details.txt | parallel \
            --max-procs 10 \
            --max-replace-args 10000 \
            --pipe \
            "wget \
              --no-verbose \
              --tries 3 \
              --waitretry 10 \
              --retry-on-http-error 500,503 \
              --user-agent '${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}' \
              --directory-prefix ./ajax-details-raw/ \
              --method POST \
              --input-file -" || true
      - name: Extract Details
        run: |
          mkdir ./ajax-details/
          for i in "./ajax-details-raw/detail?"*; do
            sed "s/)]}'$//" "$i" > "./ajax-details/$(echo "$i" | cut -d'=' -f3).json"
          done
          rm -rf ./ajax-details-raw/
      #- name: Archive Details
      #  run: |
      #    zip \
      #      --junk-paths \
      #      --recurse-paths \
      #      "${{matrix.prefix}}.zip" \
      #      ./details/
      #- name: Upload Details
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: details
      #    path: "${{matrix.prefix}}.zip"
      - name: Extract Manifests
        run: |
          mkdir ../manifests && ls -1 . | parallel "jq --raw-output '.[1][1][9][0]' {} > ../manifests/{}"
        working-directory: ./ajax-details/
      - name: Archive Manifests
        run: |
          zip \
            --junk-paths \
            --recurse-paths \
            "${{matrix.prefix}}.zip" \
            ./manifests/
      - name: Upload Manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests
          path: "${{matrix.prefix}}.zip"
      - name: Extract Details
        run: |
          mkdir ../details && ls -1 . | parallel "jq '.[1][1] | {
                name: .[0][1],
                summary: .[0][6],
                description: .[1],
                category: .[0][10],
                rating: .[0][12],
                reviews: .[0][22],
                users: .[0][23],
                version: .[6],
                updated: .[7],
                size: .[25],
              }' {} > ../details/{}"
        working-directory: ./ajax-details/
      - name: Archive Details
        run: |
          zip \
            --junk-paths \
            --recurse-paths \
            "${{matrix.prefix}}.zip" \
            ./details/
      - name: Upload Details
        uses: actions/upload-artifact@v2
        with:
          name: details
          path: "${{matrix.prefix}}.zip"
